# Personalize your website info here
title:            Gareth Harman
tagline:          'MATLAB Image Processing'
description:      'Aarons Arch Nemesis'
url:              http://garethharman.github.io
author:
  name:           'Gareth Harman'
  url:            https://twitter.com/ghostmimosa

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /